name: Commit Formatting
on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      # Ejecuta Prettier para formatear el código del commit.
      - name: Format code
        # Ref: https://github.com/marketplace/actions/prettier-action
        uses: creyD/prettier_action@v4.3
        with:
          # Prettier CLI options: https://prettier.io/docs/en/cli
          prettier_options: --write . --config ./.prettierrc --ignore-path .prettierignore
          same_commit: True
